### ISSUE TITLE
Support for new models (AS50S2SF1FA-B)

### ISSUE THREAD

**Issue by Anzic23** [oxystin/homebridge-haier-air-conditioner#3]
New models use a different connection type and a different application, not SmartAir2, but hOn. Is there any way to add them to the plugin? When adding in the standard way, I get an error:
```
Exception: Error: connect ECONNREFUSED 192.168.1.233:56800
Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.1.233:56800
Error: connect ECONNREFUSED 192.168.1.233:56800 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
uncaught exception: connect ECONNREFUSED 192.168.1.233:56800

```

**Comment by pandizajner** [comment]
Hey! Upvoting this request. I'm having the same issue. All the details (IP, MAC) typed correctly, but the connection cannot be established. Any chance to fix/update this plugin for new models support?

Thanks!

**Comment by lucaesse** [comment]
Up! I’m in the same situation… Pleeeeeease 🥹

**Comment by phanosp** [comment]
hi and thanks for your effort. My hair ac model reported on the smartair2 (iphone) app is AS35TADHRA and I can report that a lot of the features works. one of the features that I can tell is not working is getting and setting the fan

**Comment by waldo9** [comment]
I have the same problem. Any info on an update for updates models?

**Comment by eduo** [comment]
> New models use a different connection type and a different application, not SmartAir2, but hOn. Is there any way to add them to the plugin? When adding in the standard way, I get an error:
> 
> ```
> Exception: Error: connect ECONNREFUSED 192.168.1.233:56800
> Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.1.233:56800
> Error: connect ECONNREFUSED 192.168.1.233:56800 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
> uncaught exception: connect ECONNREFUSED 192.168.1.233:56800
> ```

Ah. I see I'm not the only one with the issue. What a shame, I was so excited to get this thing into HomeKit :D

**Comment by mazafra1** [comment]
Same happens with model AS35TAMHRA-C.

**Comment by gNeeUs** [comment]
Ditto error for models AS50S2SF1FA-BH and AS25S2SF1FA-BH, both operated with the hOn app.

**Comment by naim1921** [comment]
Works with Haier Tibio 12, but sometimes Siri fail to operate. 

[10/6/2022, 8:06:24 PM] Error: connect EALREADY 192.168.0.21:56800 - Local (192.168.0.17:55837)
    at internalConnect (node:net:953:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1044:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[10/6/2022, 8:06:24 PM] Got SIGTERM, shutting down Homebridge...
[10/6/2022, 8:06:27 PM] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "connection timeout error".

**Comment by AndrewKite** [comment]
Unable to connect with ducted model adh125h1erg, using the HI-WB101DEI Wi-Fi module.

**Comment by ahilmathew** [comment]
Same error on model 1U71RACFRA using the SmartHQ app.

**Comment by yendrek1984** [comment]
same problem, is it possible to ask someone to fix it

**Comment by blazejpawlak** [comment]
Same for Haier `AS352SF1FA-WH` model.

**Comment by ioBandit** [comment]
Model AS50S2SD1FA-CL works fine with standard settings
